version: '3'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  app:
    build: ./
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment: 
      - REDIS_URL=redis://cache
